/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GoodsReceiptIndexRouteImport } from './routes/goods-receipt/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as PurchaseOrdersIndexRouteImport } from './routes/purchase-orders/index'
import { Route as PurchaseRequestsIndexRouteImport } from './routes/purchase-requests/index'
import { Route as PurchaseRequestsNewRouteImport } from './routes/purchase-requests/new'
import { Route as PurchaseOrdersOrderIdIndexRouteImport } from './routes/purchase-orders/$orderId/index'
import { Route as PurchaseRequestsRequestIdIndexRouteImport } from './routes/purchase-requests/$requestId/index'
import { Route as PurchaseRequestsRequestIdEditRouteImport } from './routes/purchase-requests/$requestId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodsReceiptIndexRoute = GoodsReceiptIndexRouteImport.update({
  id: '/goods-receipt/',
  path: '/goods-receipt/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersIndexRoute = PurchaseOrdersIndexRouteImport.update({
  id: '/purchase-orders/',
  path: '/purchase-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRequestsIndexRoute = PurchaseRequestsIndexRouteImport.update({
  id: '/purchase-requests/',
  path: '/purchase-requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRequestsNewRoute = PurchaseRequestsNewRouteImport.update({
  id: '/purchase-requests/new',
  path: '/purchase-requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersOrderIdIndexRoute =
  PurchaseOrdersOrderIdIndexRouteImport.update({
    id: '/purchase-orders/$orderId/',
    path: '/purchase-orders/$orderId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PurchaseRequestsRequestIdIndexRoute =
  PurchaseRequestsRequestIdIndexRouteImport.update({
    id: '/purchase-requests/$requestId/',
    path: '/purchase-requests/$requestId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PurchaseRequestsRequestIdEditRoute =
  PurchaseRequestsRequestIdEditRouteImport.update({
    id: '/purchase-requests/$requestId/edit',
    path: '/purchase-requests/$requestId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/purchase-requests/new': typeof PurchaseRequestsNewRoute
  '/goods-receipt/': typeof GoodsReceiptIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/purchase-orders/': typeof PurchaseOrdersIndexRoute
  '/purchase-requests/': typeof PurchaseRequestsIndexRoute
  '/purchase-requests/$requestId/edit': typeof PurchaseRequestsRequestIdEditRoute
  '/purchase-orders/$orderId/': typeof PurchaseOrdersOrderIdIndexRoute
  '/purchase-requests/$requestId/': typeof PurchaseRequestsRequestIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/purchase-requests/new': typeof PurchaseRequestsNewRoute
  '/goods-receipt': typeof GoodsReceiptIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/purchase-orders': typeof PurchaseOrdersIndexRoute
  '/purchase-requests': typeof PurchaseRequestsIndexRoute
  '/purchase-requests/$requestId/edit': typeof PurchaseRequestsRequestIdEditRoute
  '/purchase-orders/$orderId': typeof PurchaseOrdersOrderIdIndexRoute
  '/purchase-requests/$requestId': typeof PurchaseRequestsRequestIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/purchase-requests/new': typeof PurchaseRequestsNewRoute
  '/goods-receipt/': typeof GoodsReceiptIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/purchase-orders/': typeof PurchaseOrdersIndexRoute
  '/purchase-requests/': typeof PurchaseRequestsIndexRoute
  '/purchase-requests/$requestId/edit': typeof PurchaseRequestsRequestIdEditRoute
  '/purchase-orders/$orderId/': typeof PurchaseOrdersOrderIdIndexRoute
  '/purchase-requests/$requestId/': typeof PurchaseRequestsRequestIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reports'
    | '/settings'
    | '/purchase-requests/new'
    | '/goods-receipt/'
    | '/inventory/'
    | '/purchase-orders/'
    | '/purchase-requests/'
    | '/purchase-requests/$requestId/edit'
    | '/purchase-orders/$orderId/'
    | '/purchase-requests/$requestId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reports'
    | '/settings'
    | '/purchase-requests/new'
    | '/goods-receipt'
    | '/inventory'
    | '/purchase-orders'
    | '/purchase-requests'
    | '/purchase-requests/$requestId/edit'
    | '/purchase-orders/$orderId'
    | '/purchase-requests/$requestId'
  id:
    | '__root__'
    | '/'
    | '/reports'
    | '/settings'
    | '/purchase-requests/new'
    | '/goods-receipt/'
    | '/inventory/'
    | '/purchase-orders/'
    | '/purchase-requests/'
    | '/purchase-requests/$requestId/edit'
    | '/purchase-orders/$orderId/'
    | '/purchase-requests/$requestId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  PurchaseRequestsNewRoute: typeof PurchaseRequestsNewRoute
  GoodsReceiptIndexRoute: typeof GoodsReceiptIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  PurchaseOrdersIndexRoute: typeof PurchaseOrdersIndexRoute
  PurchaseRequestsIndexRoute: typeof PurchaseRequestsIndexRoute
  PurchaseRequestsRequestIdEditRoute: typeof PurchaseRequestsRequestIdEditRoute
  PurchaseOrdersOrderIdIndexRoute: typeof PurchaseOrdersOrderIdIndexRoute
  PurchaseRequestsRequestIdIndexRoute: typeof PurchaseRequestsRequestIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goods-receipt/': {
      id: '/goods-receipt/'
      path: '/goods-receipt'
      fullPath: '/goods-receipt/'
      preLoaderRoute: typeof GoodsReceiptIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders/': {
      id: '/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof PurchaseOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-requests/': {
      id: '/purchase-requests/'
      path: '/purchase-requests'
      fullPath: '/purchase-requests/'
      preLoaderRoute: typeof PurchaseRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-requests/new': {
      id: '/purchase-requests/new'
      path: '/purchase-requests/new'
      fullPath: '/purchase-requests/new'
      preLoaderRoute: typeof PurchaseRequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders/$orderId/': {
      id: '/purchase-orders/$orderId/'
      path: '/purchase-orders/$orderId'
      fullPath: '/purchase-orders/$orderId/'
      preLoaderRoute: typeof PurchaseOrdersOrderIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-requests/$requestId/': {
      id: '/purchase-requests/$requestId/'
      path: '/purchase-requests/$requestId'
      fullPath: '/purchase-requests/$requestId/'
      preLoaderRoute: typeof PurchaseRequestsRequestIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-requests/$requestId/edit': {
      id: '/purchase-requests/$requestId/edit'
      path: '/purchase-requests/$requestId/edit'
      fullPath: '/purchase-requests/$requestId/edit'
      preLoaderRoute: typeof PurchaseRequestsRequestIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  PurchaseRequestsNewRoute: PurchaseRequestsNewRoute,
  GoodsReceiptIndexRoute: GoodsReceiptIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  PurchaseOrdersIndexRoute: PurchaseOrdersIndexRoute,
  PurchaseRequestsIndexRoute: PurchaseRequestsIndexRoute,
  PurchaseRequestsRequestIdEditRoute: PurchaseRequestsRequestIdEditRoute,
  PurchaseOrdersOrderIdIndexRoute: PurchaseOrdersOrderIdIndexRoute,
  PurchaseRequestsRequestIdIndexRoute: PurchaseRequestsRequestIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
